---
abstract: 'Blends syntax-highlighted code and pod in one XHTML document.'
author:
  - 'Curtis Jewell <csjewell@cpan.org>'
build_requires:
  File::Slurp: 9999.13
  IO::CaptureOutput: 0.1102
  Test::LongString: 0.13
  Test::More: 0.88
configure_requires:
  Module::Build: 0.33
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Simple-XHTML-BlendedCode
provides:
  Pod::Simple::XHTML::BlendedCode:
    file: lib/Pod/Simple/XHTML/BlendedCode.pm
    version: 1.003
  Pod::Simple::XHTML::BlendedCode::Blender:
    file: lib/Pod/Simple/XHTML/BlendedCode/Blender.pm
    version: 1.000
requires:
  IO::String: 1.08
  PPI::HTML: 1.08
  Pod::Parser: 1.37
  Pod::Simple::XHTML: 3.14
  parent: 0.223
  perl: 5.008001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Pod-Simple-XHTML-BlendedCode
  homepage: http://csjewell.comyr.com/
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/csjewell/pod-simple-xhtml-blendedcode
version: 1.003
